### ISSUE TITLE
Cannot login to KAUI using the "Getting Started" Docker container

### ISSUE THREAD

**Issue by ZacharyKlein** [killbill/killbill-admin-ui#240]
Here's the steps I've performed (following the docs here:https://docs.killbill.io/0.20/getting_started.html)

1. `docker-machine create -d virtualbox --virtualbox-memory "2048" killbill`
2. `eval $(docker-machine env killbill)`
3. `docker-machine ip killbill` (retrieved IP: `http://192.168.99.100`)
4. Created `docker-compose.yml` (shown below)
5. `docker-compose up`
6. Accessed `http://192.168.99.100:9090`, attempted login with `admin`/`password`

I get a the message "Kill Bill is unavailable", which I see is associated with a connection refused. 

Haven't spent additional time on this, just checking this out for evaluation purposes. But following the steps in the "Getting Started" guide doesn't seem to be sufficient to getting the Docker container set up.

**Comment by ZacharyKlein** [comment]
`docker-compose.yml`

```
version: '3.2'
volumes:
  db:
services:
  killbill:
    image: killbill/killbill:0.20.0
    ports:
      - "8080:8080"
      - "8000:8000"
      - "12345:12345"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - ENV_HOST_IP=192.168.99.100
  kaui:
    image: killbill/kaui:1.0.4
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080
  db:
    image: killbill/mariadb:0.20
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
```
