### ISSUE TITLE
Install New Plugins at /kpm/plugins returns error in stock setup

### ISSUE THREAD

**Issue by jblachly** [killbill/killbill-admin-ui#332]
KAUI in a stock setup using the public Docker images for KillBill, KAUI, and killbill/mariadb with example docker-compose.yml works well with no seeming problems, except that clicking "Install New Plugins" does not work.

The link goes to `<domain>/kpm/plugins` but when clicking, there is a delay of ~15 secs and then finally a blank page with a red error message "We're sorry, but something went wrong."

I'm using the latest published version tags (0.24.0; 2.0.11)

```
killbill:
    image: killbill/killbill:0.24.0
    restart: always
    volumes:
      - ./killbill/killbill.properties:/var/lib/killbill/killbill.properties:ro
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://mariadb:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=${KILLBILL_DAO_PASSWORD}

  kaui:
    image: killbill/kaui:2.0.11
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://mariadb:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=${KILLBILL_DAO_PASSWORD}
      - KAUI_KILLBILL_URL=http://killbill:8080
```
(some labels and network tags removed)
