### ISSUE TITLE
run_in_parallel can lead to infinite loop of calls

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-admin-ui#49]
I ran into the following use case when using the following database config:

```
test:
  adapter: mysql2
  database: kaui_test
  username: <%= ENV.fetch('MYSQL_USER', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'root') %>
  host: 127.0.0.1
  port: 3306
  pool: 5
  timeout: 5000
```

When showing an account page, we do 5 calls in parallel (fetch_upcoming_invoice_date, fetch_overdue_state, fetch_account_tags, fetch_account_emails, fetch_payment_methods), and somehow once of the task end up with an exception `#<ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.001 seconds)>`

*There is a question already here on why we end up with a 5 sec timeout, but this is not the point of this bug*

The point of this bug is that because of the exception, all 5 tasks get restarted forever and we have an infinite loop of requests.
